name: "publish"

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max_old_space_size=6000"

jobs:
  publish-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Print GitHub workspace
        run: echo "${{ github.workspace }}"

      - name: Add node_modules to PATH
        run: echo "${{ github.workspace }}" >> $GITHUB_PATH

      - name: Clone Arti Repository
        run: |
          git clone --branch main --single-branch https://gitlab.torproject.org/tpo/core/arti.git ../arti

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.0.11902837"

      - name: Add NDK toolchain to PATH
        run: echo "$ANDROID_HOME/ndk/27.0.11902837/toolchains/llvm/prebuilt/linux-x86_64/bin" >> "$GITHUB_PATH"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Install dependencies
        run: pnpm install

      - name: Build app bundle
        run: pnpm tauri android build -v
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837

      #- name: Extract Android signing key from env
      #  run: |
      #    echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" > src-tauri/gen/android/release.jks.base64
      #    base64 -d src-tauri/gen/android/release.jks.base64 > src-tauri/gen/android/release.decrypted.jks

     
      #- name: Sign APK
      #  run: |
      #    ${{ env.ANDROID_HOME }}/build-tools/34.0.0/apksigner sign --ks src-tauri/gen/android/release.decrypted.jks \
      #      --ks-key-alias ${{ secrets.ANDROID_RELEASE_KEY }} \
      #      --ks-pass pass:${{ secrets.ANDROID_RELEASE_PASSWORD }} \
      #      --key-pass pass:${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }} \
      #      --out src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-signed.apk \
      #      src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk

      - name: Get Node project version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Rename APK file
        run: |
          mv ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk ./src-tauri/gen/android/app/build/outputs/apk/universal/release/letscage-mobile-${{ steps.package-version.outputs.current-version }}.apk

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: App v${{ steps.package-version.outputs.current-version }}
          tag_name: v${{ steps.package-version.outputs.current-version }}
          generate_release_notes: true
          files: |
            ./src-tauri/gen/android/app/build/outputs/apk/universal/release/letscage-mobile-${{ steps.package-version.outputs.current-version }}.apk

  publish-tauri:
    if: false # Temporarily skipping this job
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Print GitHub workspace
        run: echo "${{ github.workspace }}"

      - name: Clone Arti Repository
        run: |
          git clone --branch main --single-branch https://gitlab.torproject.org/tpo/core/arti.git ../arti

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: yarn install

      - name: Test build
        run: npm run tauri build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: letscage-v__VERSION__
          releaseName: 'Letscage v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}